services:
  sollent.doctrine_smart_bundle.doctrine_entity_creator:
    class: sollent\DoctrineSmartBundle\EntityCreator\DoctrineEntityCreator
    autoconfigure: true
    autowire: true
  sollent.doctrine_smart_bundle.doctrine_entity_class_repository:
    class: sollent\DoctrineSmartBundle\Repository\DoctrineEntityClassRepository
    autoconfigure: true
    autowire: true
    arguments: [ '@doctrine.orm.entity_manager' ]
  sollent\DoctrineSmartBundle\Controller\EntityCreatorController:
    autoconfigure: true
    autowire: true
    arguments:
      - '@sollent.doctrine_smart_bundle.doctrine_entity_class_repository'
      - '@sollent.doctrine_smart_bundle.doctrine_entity_creator'
